### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by SohanTirpude** [gauntface/simple-push-demo-backend#3]
Hello,

I would like to know how to use this. Is there any documentation available? I want to use python as a back-end to send push notification to various users, but I am unable to find any good resources from which I can understand exactly how to achieve it. Kindly let me know, if you have any idea. Thanks.

**Comment by gauntface** [comment]
This is specifically for simple push demo, not for general use. See: https://github.com/web-push-libs/pywebpush for what you want.
